### ISSUE TITLE
Omregistrer og få Oslonøkkelen-domene inn under Origo

### ISSUE THREAD

**Issue by yngvark** [oslokommune/kjoremiljo-admin-issues#10]
# ToDo

* [x] Registrer oslonøkkelen.com hos Origo (asap)
* [x] Omregistrer oslonøkkelen.no fra Rune Sandland til Origo
* [ ] Bytt kontaktinfo på domene fra Yngvar til noen andre?

# Detaljer

Melding fra @eivindlu:

Kjapt spørsmål: Oslonøkkelen har et domene som står registrert på 
[@Rune Sandland](https://oslokommune.slack.com/team/U7MLR7QTT), de ønsker å få omregistrert dette slik at det står på Oslo Origo. Erlend nevnte mente at det kanskje var like greit for dere (kjøremiljø) å legge det inn i R53.

[...] virker dette logisk for dere?

**Comment by leiacf** [comment]
Fikk ny epost om dette i dag. 

Det opprinnelige ønsket er å overføre eierskap av oslonøkkelen.no fra Rune til Origo. I tillegg ønsker de å registrere oslonøkkelen.com hos Origo.

Har etterspurt en vurdering på hvor mye det haster. I utgangspunktet har vi jo sagt (i Slack) at det kan ta litt tid.

**Comment by leiacf** [comment]
Ny epost: Haster visst ikke å flytte, men haster å registrere .com så ingen stjeler det!

**Comment by yngvark** [comment]
Jeg har registert oslonøkkelen.com i AWS Route 53. Og verifisert epost.

**Comment by kmoberg** [comment]
AWS støtter ikke `.no` domener, så domenet kan ikke flyttes dit. Alternativ er å omregistrere domenet på Origo hos eksisterende leverandør, eller flytte til en ny registrar og omregistrere samtidig.

**Comment by kmoberg** [comment]
Domenet er nå registert på Origo!
