### ISSUE TITLE
Epic: Clean up the documentation after restructuring

### ISSUE THREAD

**Issue by leiacf** [oslokommune/kjoremiljo-admin-issues#114]
```[tasklist]
### Tasks we need to do to fix our documentation
- [ ] https://github.com/oslokommune/golden-path-iac/issues/555
- [ ] https://github.com/oslokommune/golden-path-iac/issues/549
- [ ] https://github.com/oslokommune/golden-path-iac/issues/551
- [ ] https://github.com/oslokommune/golden-path-iac/issues/550
- [ ] https://github.com/oslokommune/kjoremiljo-admin-issues/issues/82
- [ ] https://github.com/oslokommune/golden-path-iac/issues/593
- [ ] https://github.com/oslokommune/golden-path-iac/issues/664
- [ ] https://github.com/oslokommune/golden-path-iac/issues/665
- [ ] https://github.com/oslokommune/golden-path-iac/issues/666
- [ ] https://github.com/oslokommune/golden-path-iac/issues/660
- [ ] https://github.com/oslokommune/golden-path-iac/issues/695
- [ ] https://github.com/oslokommune/golden-path-iac/issues/696
- [ ] https://github.com/oslokommune/golden-path-iac/issues/685
- [ ] https://github.com/oslokommune/golden-path-iac/issues/687
- [ ] https://github.com/oslokommune/golden-path-iac/issues/708
- [ ] https://github.com/oslokommune/golden-path-iac/issues/720
```

**Comment by leiacf** [comment]
We had several documentation task list issues, with no clear distinction, and with some of the issues being in more than one list. 

I cleaned this up and moved everything that we still hadn't done into one list (then separated it again and moved the pure design tasks out into a separate list, but now the distinction is more clear)

I will close this one as completed because it now only consists of tasks we've already done.
