### ISSUE TITLE
Finne og evt fjerne IAM-brukere/SAML-roller/Keycloak IDP

### ISSUE THREAD

**Issue by yngvark** [oslokommune/kjoremiljo-admin-issues#122]
# Beskrivelse

```[tasklist]
### Tasks
- [ ] Gjøre tingene nevnt i https://oslokommune.slack.com/archives/C018EFCSC4W/p1677770221750919
- [ ] Si ifra til @endremm på Slack når det er gjort
- [ ] Fjerne gamle IDP-profiler for EKS (har typisk `eks` i navnet)
```

# Motivasjon

Se https://oslokommune.slack.com/archives/C018EFCSC4W/p1677770221750919

**Comment by kmoberg** [comment]
Fjernet i kontoene:
* kjoremiljo-dev
* kjoremiljo-prod
* origo-prod
