### ISSUE TITLE
O: Kim skal aldri være redd for dataene sine når hen bruker Brolagt sti

### ISSUE THREAD

**Issue by leiacf** [oslokommune/kjoremiljo-admin-issues#136]
### Objective: Kim skal aldri være redd for dataene sine når hen bruker Brolagt sti

```[tasklist]
### Key Results
- [ ] https://github.com/oslokommune/kjoremiljo-admin-issues/issues/141
- [ ] https://github.com/oslokommune/kjoremiljo-admin-issues/issues/142
- [ ] https://github.com/oslokommune/kjoremiljo-admin-issues/issues/143
```

**Comment by leiacf** [comment]
Lukker denne. Den erstattes av #176
