### ISSUE TITLE
O: Kim vet hva Brolagt sti er

### ISSUE THREAD

**Issue by leiacf** [oslokommune/kjoremiljo-admin-issues#137]
### Objective: Kim vet hva Brolagt sti er

```[tasklist]
### Key Results
- [ ] https://github.com/oslokommune/kjoremiljo-admin-issues/issues/144
- [ ] https://github.com/oslokommune/kjoremiljo-admin-issues/issues/145
- [ ] https://github.com/oslokommune/kjoremiljo-admin-issues/issues/146
- [ ] https://github.com/oslokommune/kjoremiljo-admin-issues/issues/162
```

**Comment by leiacf** [comment]
Lukker denne, den erstattes av #180
