### ISSUE TITLE
🔑 Vi skal tette alle hull i grunnoppsettet

### ISSUE THREAD

**Issue by leiacf** [oslokommune/kjoremiljo-admin-issues#139]
```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```
```[tasklist]
### Aktiviteter
- [x] Gå igjennom og link til riktige issues her (flere av disse har issues allerede)
- [x] Definere grunnoppsettet (Løsning: issuene i dette issuet er grunnoppsettet)
- [x] Bli enige om "definition of done"
- [ ] Hvordan tar vi hensyn til hva teamene gjorde i migreringsperioden?
- [x] Flate ut ECS-modul
- [x] Fokusuke
- [ ] https://github.com/oslokommune/golden-path-iac/issues/398
- [ ] https://github.com/oslokommune/origo-aws-mgmt-iac/issues/12
- [ ] https://github.com/oslokommune/golden-path-iac/issues/243
- [ ] https://github.com/oslokommune/golden-path-iac/issues/517
- [ ] https://github.com/oslokommune/golden-path-iac/issues/629
- [ ] https://github.com/oslokommune/kjoremiljo-confidential-issues/issues/42
- [ ] oslokommune/kjoremiljo-confidential-issues#27
- [ ] https://github.com/oslokommune/golden-path-iac/issues/649
- [ ] https://github.com/oslokommune/kjoremiljo-confidential-issues/issues/44
- [ ] https://github.com/oslokommune/golden-path-iac/issues/878
- [ ] https://github.com/oslokommune/golden-path-iac/issues/332
- [ ] https://github.com/oslokommune/golden-path-iac/issues/30
- [ ] https://github.com/oslokommune/golden-path-iac/issues/630
- [ ] https://github.com/oslokommune/golden-path-iac/issues/423
- [ ] https://github.com/oslokommune/golden-path-iac/issues/226
- [ ] https://github.com/oslokommune/golden-path-iac/issues/342
```

**Comment by leiacf** [comment]
Legger dette nøkkelresultatet i "Later" -> Perioden er ferdig, men vi har en del historikk og sortering her vi kanskje burde ta vare på?

@yngvark Hvis du tenker historikken er ivaretatt på andre måter kan vi eventuelt lukke denne epicen også.

**Comment by yngvark** [comment]
Lukker denne. Key result https://github.com/oslokommune/kjoremiljo-admin-issues/issues/175 tar over for dette.
