### ISSUE TITLE
Planlegg onboarding barnehageplass / vitalia mot brolagt sti

### ISSUE THREAD

**Issue by Kielo87** [oslokommune/kjoremiljo-admin-issues#14]
Oppgaver står i https://docs.google.com/document/d/1floocpUnVSGiMZ-ZCUHEkIQEkXH6JQo3mhnO-fvfkpw/edit#heading=h.21tp3t18dn1s

# ToDo
* [x] Fyll ut plan i et googledoc, som beskriver hva vi skal gjøre: https://docs.google.com/document/d/1gIwof1M3FtCzYvUdZp3JFBaEfJgtVntHgJzdA7eoUro/edit
* [x] Vurder: Det funka bra med et prosjekt board (Github project board) som vi bruker under onboardingen. Da er alle omforent med hva vi skal igjennom og hvor vi er i løypa. Hvis vi ønsker dette, må det settes opp.
* [x] Finn ut av om hvem som stiller fra Kjøremiljø. Noen / Alle?
* [x] Annet relevant
* [x] @leiacf - Sammenstille https://docs.google.com/document/d/1NANtRMVZAq7dZmovapCh9pkc5DTuzcwKGOScovBjv9M/edit#heading=h.m6pltl7bno7g og https://docs.google.com/document/d/1gIwof1M3FtCzYvUdZp3JFBaEfJgtVntHgJzdA7eoUro/edit#heading=h.e3uq26bpwhw0
* [x] Skrive ned nøyaktig plan for barnehageplass og vitalia i googledoc. Evt: Diskuter hvordan vi er omforent om planen framover. Motivasjon: Vi trenger å være omforent om planen framover, i.e. hva som skjer framover og når. Da er det mye lettere for oss å spotte problemer med planen.
  * [x] @yngvark - [Barnehageplass](https://docs.google.com/document/d/1PRRldVPJsJ9YO0VvjFM8SPEHF6LQpfTbP3HRzMautDo/edit)
  * [x] [Vitalia](https://docs.google.com/document/d/1asbcD4YVuY948bAjkWAsAW3s_f8Q39Oa-mp-oMoCkw4)

# Ressurser
* Se onboarding dokumenter fra Okctl: https://drive.google.com/drive/u/0/folders/18E3BA3dPZ9JunRDKorQvMUPa9cSiw7yB

**Comment by leiacf** [comment]
Hva er egentlig definition of done på denne? Når vi er ferdig med samarbeidsmøtet i morgen, når vi har hatt første møte med Vitalia, eller noe annet?

**Comment by yngvark** [comment]
Jeg vurderte å lukke den, men lot den stå åpen siden jeg heller ikke var sikker. Jeg tenker vi finner ut av det i samarbeidsmøtet.

**Comment by leiacf** [comment]
Tenker vi kan lukke denne etter møtet med Vitalia i dag :)

**Comment by yngvark** [comment]
Jeg la til to nye punkter i ToDo lista overst.

**Comment by yngvark** [comment]
Vi kan fylle ut plan for Vitalia etter vi har hatt møte med de.

**Comment by leiacf** [comment]
Jeg flyttet sammenstillingen av doumenter til #83 - så lukker denne
