### ISSUE TITLE
🔑  Vi skal tette alle hull i dokumentasjonen

### ISSUE THREAD

**Issue by leiacf** [oslokommune/kjoremiljo-admin-issues#140]
```[tasklist]
### Aktiviteter
- [ ] https://github.com/oslokommune/kjoremiljo-admin-issues/issues/152
- [ ] https://github.com/oslokommune/kjoremiljo-admin-issues/issues/114
- [ ] https://github.com/oslokommune/golden-path-iac/issues/518
- [ ] https://github.com/oslokommune/golden-path-iac/issues/488
- [ ] https://github.com/oslokommune/golden-path-iac/issues/657
- [ ] https://github.com/oslokommune/reusable-workflows/issues/73
- [ ] https://github.com/oslokommune/golden-path-iac/issues/649
- [ ] https://github.com/oslokommune/golden-path-iac/issues/579
- [ ] https://github.com/oslokommune/golden-path-iac/issues/535
- [ ] https://github.com/oslokommune/golden-path-iac/issues/741
- [ ] https://github.com/oslokommune/golden-path-iac/issues/742
- [ ] https://github.com/oslokommune/golden-path-iac/issues/552
- [ ] https://github.com/oslokommune/golden-path-iac/issues/715
- [ ] https://github.com/oslokommune/kjoremiljo-admin-issues/issues/131
- [ ] https://github.com/oslokommune/golden-path-iac/issues/727
```

**Comment by leiacf** [comment]
Samme med denne. Jeg er usikker på om vi har en like god samling et annet sted, så beholder denne epic'en og legger den i "later". 

@Kielo87 du kan eventuelt vurdere om den heller bør lukkes

**Comment by yngvark** [comment]
Lukker denne, ettersom dette er et nøkkelresultat i en periode som nå er over.

Om vi trenger oversikt, kan vi filtrere issues på label:documentation.

De av oppgavene som ikke ble fullført, kan vi prioritere på vanlig måte framover.

Utfallet av #189 vil påvirke hvilke av disse vi tar tak i, mens noen er uavhengig den  (feks #657).
