### ISSUE TITLE
KR: Vi skal gjennomføre alle relevante tiltak definert i sikkerhetsrapporten fra EY på grunnoppsettet

### ISSUE THREAD

**Issue by leiacf** [oslokommune/kjoremiljo-admin-issues#141]
```[tasklist]
### Aktiviteter
- [ ] Definer grunnoppsettet (se også #139)
- [x] Lag liste over relevante tiltak
- [x] Oppdater denne listen ved behov...
- [ ] Dokumenter hvorfor et tiltak eventuelt ikke er relevant
```

**Comment by kmoberg** [comment]
Opprettet 6 tasks i confidential issues.

**Comment by kmoberg** [comment]
Dokumentert issues som ikke gjennomføres i confidential issues.
