### ISSUE TITLE
🔑 Presentere visjonen for Brolagt sti på allmøte i september

### ISSUE THREAD

**Issue by leiacf** [oslokommune/kjoremiljo-admin-issues#145]
```[tasklist]
### Aktiviteter
- [ ] TODO: Definér og fyll ut lista
- [ ] https://github.com/oslokommune/kjoremiljo-admin-issues/issues/85
- [ ] https://github.com/oslokommune/kjoremiljo-admin-issues/issues/123
```

**Comment by leiacf** [comment]
Lukker dette da det er et tidligere nøkkelresultat. Kan gjenåpnes hvis vi trenger det på nytt.
