### ISSUE TITLE
KR: Vi skal få på plass første versjon av et outcomebasert veikart innen 3. mai

### ISSUE THREAD

**Issue by leiacf** [oslokommune/kjoremiljo-admin-issues#146]
```[tasklist]
### Aktiviteter
- [x] TODO: Definér og fyll ut lista
- [ ] https://github.com/oslokommune/kjoremiljo-admin-issues/issues/113
- [x] Brukertest veikartet
- [ ] https://github.com/oslokommune/kjoremiljo-admin-issues/issues/158
```

**Comment by leiacf** [comment]
Flytter denne til completed fordi med endringen av Key Result-tekst er denne faktisk ferdig
