### ISSUE TITLE
Fokusuke 17-21 april

### ISSUE THREAD

**Issue by leiacf** [oslokommune/kjoremiljo-admin-issues#151]
Denne oppgaven er ment som en Epic for å vise hvilke ting som må gjøres i løpet av fokusuken.

```[tasklist]
### Oppgaver
- [ ] TODO: Fyll ut denne listen under planlegging første dag
- [ ] Gjøre om nytt oppsett fra dogfood til noe teamene kan konsumere
- [ ] Skrive dokumentasjon for det nye oppsettet
- [ ] https://github.com/oslokommune/kjoremiljo-admin-issues/issues/114
```

**Comment by leiacf** [comment]
Gjennomført
