### ISSUE TITLE
Epic: Avholde fokusuke 17-21 april

### ISSUE THREAD

**Issue by leiacf** [oslokommune/kjoremiljo-admin-issues#152]
### Bakgrunn

I forbindelse med at alle teamene migrerte til Brolagt sti samtidig ble en del ting gjort som hastverksarbeid og utsatt til senere. 

Nå har vi dermed en litt utdatert dokumentasjon, med flere hull, som bærer veldig preg av at flere har skrevet på den samtidig.

I tillegg jobber vi med å restrukturere grunnoppsettet vårt.

Vi ønsker derfor å avholde en fokusuke / hackaton hvor vi sitter samlet og jobber med disse tingene. Tanken er at vi går igjennom dokumentasjonen, og fikser de problemene vi kommer over underveis, enten det er språklig, fylle tomme sider, rette opp i utdaterte sider, eller fikse feil i selve koden..

### OKR

Dette treffer #135 

```[tasklist]
### Oppgaver
- [x] Booke møterom for uka
- [x] Kalle inn teamet til langt møte
- [x] Planlegge løst hvordan uka skal se ut
- [x] Fylle ut https://miro.com/app/board/uXjVMZ2Y9Rw=/
```
