### ISSUE TITLE
🔑 Vitalia har satt opp Brolagt sti i dev

### ISSUE THREAD

**Issue by leiacf** [oslokommune/kjoremiljo-admin-issues#173]
### Beskrivelse

Vitalia har alt de trenger for å sette opp Brolagt sti i dev, inkludert CI/CD. Måloppnåelse kommer delvis an på når teamet har tid til å jobbe med oss.

```[tasklist]
### Komponenter (som telles)
- [x] Sette opp CI/CD
- [x] Sette opp databasebruker(e)
```

```[tasklist]
### Stacks (som telles)
- [x] app-common
- [x] app-hub
- [x] certificates
- [x] databases
- [x] dns
- [x] document-storage
- [x] iam
- [x] load-balancing (inkludert NLB)
- [x] networking
- [x] rds-bastion
- [x] remote_state
- [x] security-groups
```
