### ISSUE TITLE
Epic Planning

### ISSUE THREAD

**Issue by leiacf** [oslokommune/kjoremiljo-admin-issues#83]
After discussing with Yngvar and Mira, there are a lot of admin tasks we should do / follow up on. 

Most of them are small, but just to have the list somewhere I'll create it here. We can split it up if we see the need.

- [x] Combine [Fremdriftsplan](https://docs.google.com/document/d/1BieIHrm7dNMOQSKEOyCzqtrlzwoEAqWOo_-mTCiuqcI) and [Strategi](https://docs.google.com/document/d/18NEYUJXy-Gx4VNG97mE1S8bCrIiFwZIJvPXK642H5yk/edit?usp=share_link)
- [x] Update and expand on the rest of the resulting document
- [x] Look into creating an overall chart of tasks needed in the days ahead, use the document above as guideline
- [x] Combine [Gjennomføring av første møte](https://docs.google.com/document/d/1gIwof1M3FtCzYvUdZp3JFBaEfJgtVntHgJzdA7eoUro/) and [Plan for samarbeid](https://docs.google.com/document/d/1NANtRMVZAq7dZmovapCh9pkc5DTuzcwKGOScovBjv9M/)
- [x] Clean up and reorganize Google Drive
- [x] Go through the various documents written about migration in earlier stages and double check if we have everything covered

**Comment by leiacf** [comment]
There might be some info in [this documetnt](https://docs.google.com/document/d/11rfLqgUaZ7N1CCTprDVjtMZZI9BnUZfwH8Vtb8r3MF0) that could be incorporated in the actual plan.

**Comment by leiacf** [comment]
Testing slack commenting

**Comment by leiacf** [comment]
Har ikke fått kommet videre her fordi så mange ting har kommet i veien, så flytter den ut av "WiP".

**Comment by leiacf** [comment]
Teamene har kommet over, så avslutter denne. Eventuelle nye planer må ta utgangspunkt i hva vi har nå, ikke hva vi hadde.
