### ISSUE TITLE
Rydde opp i Slack-kanalkabbalen

### ISSUE THREAD

**Issue by Kielo87** [oslokommune/kjoremiljo-admin-issues#89]
## Beskrivelse
Vi har behov til å rydde opp i Slack-kanaler. Det blir litt for mye for brukerne å forholde seg til og vi ser overlapp på noen av kanalene.

### Kanaler som er i bruk nå
**Internkanaler**
#origo-kjøremiljø-intern
#kjøremiljø-brukerinnsikt
#kjøremiljø-aktiviteter
#kjøremiljø-feeds

**Brolagt sti / kjøremiljø-tematikk**
#origo-kjøremiljø
#origo-kjøremiljø-superbrukere
#origo-kjøremiljø-viktig
#origo-kjøremiljø-support

**okctl**
#okctl-viktig
(#origo-kjøremiljø-support)

**Temp kanaler**
#temp-kjøremiljø-booking-kosekrok
#temp-kjøremiljø-helsedata-kosekrok
#temp-golden-path-observability
#temp-julius-ecs-notifications

## Motivasjon
Vi vil at brukerne får riktig informasjon i riktige steder og føler at de har kontroll over det. Vi må også selv ha kontroll og oversikt over kanalene.

## ToDO
- [x] Definer en tydlig bruksområde til hvert kanal
- [x] Arkiver overflødige kanaler
- [x] Endre navn på kanaler som har behov for det
- [x] Oppdater dokumentasjon til å matche info om kanalene

**Comment by Kielo87** [comment]
Første delen er klar.

#superbrukerforum heter nå #origo-infrastruktur (basert på en poll på teknologiavdeling sin kanal).

### Kanaler som ble arkivert
#origo-aws-samarbeid
#origo-fagforum-aws
#origo-kjøremiljø
#temp-golden-path-observability

Har en melding ut på #temp-kjøremiljø-helsedata-kosekrok for å sjekke om den kan også arkiveres.

**Comment by Kielo87** [comment]
Alle kanaler som skal arkiveres er arkivert. Må oppdatere dokumentasjon senere
